const {
  GITHUB_TOKEN, OPENROUTER_API_KEY, ISSUE_NUMBER, ISSUE_TITLE,
  ISSUE_BODY, ISSUE_LABELS, REPO_OWNER, REPO_NAME,
} = process.env;

const GITHUB_API = "https://api.github.com";
const REPO = `${REPO_OWNER}/${REPO_NAME}`;

async function githubRequest(endpoint, method = "GET", body = null) {
  const res = await fetch(`${GITHUB_API}${endpoint}`, {
    method,
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : null,
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API ${method} ${endpoint} failed ${res.status}: ${text}`);
  }
  return res.status === 204 ? null : res.json();
}

async function postComment(comment) {
  return githubRequest(`/repos/${REPO}/issues/${ISSUE_NUMBER}/comments`, "POST", { body: comment });
}

async function addLabels(labels) {
  return githubRequest(`/repos/${REPO}/issues/${ISSUE_NUMBER}/labels`, "POST", { labels });
}

async function analyseIssue() {
  const systemPrompt = `You are an expert Triage Agent for a GitHub repository called "${REPO}".
Your job is to read a newly opened issue and produce a structured engineering brief.

The repo is a Node.js + Express habit tracker with a vanilla JS frontend and Jest tests.
Key files: backend/habits.js (core logic), backend/server.js (API), frontend/app.js (UI), tests/habits.test.js.

Respond with ONLY valid JSON (no markdown fences, no extra text):
{
  "summary": "One-sentence summary",
  "type": "bug | feature | chore | question",
  "priority": "high | medium | low",
  "likely_root_cause": "Your analysis or N/A for features",
  "files_to_inspect": ["file/paths"],
  "proposed_fix": "How to resolve this",
  "tests_to_add": "What tests to add or update",
  "risk_notes": "Risks or edge cases",
  "ready_for_implementation": true
}

Set ready_for_implementation to true if clear and actionable, false if it needs more info.`;

  const userMessage = `## New Issue #${ISSUE_NUMBER}\n\n**Title:** ${ISSUE_TITLE}\n\n**Labels:** ${ISSUE_LABELS || "none"}\n\n**Description:**\n${ISSUE_BODY || "(no description)"}`;

  const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${OPENROUTER_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "anthropic/claude-sonnet-4",
      max_tokens: 1024,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userMessage },
      ],
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`OpenRouter API failed ${res.status}: ${text}`);
  }

  const data = await res.json();
  const text = data.choices[0].message.content.trim();

  try {
    return JSON.parse(text);
  } catch {
    return JSON.parse(text.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim());
  }
}

function formatComment(a) {
  const ready = a.ready_for_implementation;
  return `## 🤖 Triage Agent — Engineering Brief

| Field | Detail |
|-------|--------|
| **Summary** | ${a.summary} |
| **Type** | \`${a.type}\` |
| **Priority** | \`${a.priority}\` |
| **Ready** | ${ready ? "✅ Yes" : "⏳ Needs more info"} |

### 🔍 Likely Root Cause
${a.likely_root_cause}

### 📁 Files to Inspect
${a.files_to_inspect.map((f) => "- \`" + f + "\`").join("\n")}

### 🛠️ Proposed Fix
${a.proposed_fix}

### 🧪 Tests to Add / Update
${a.tests_to_add}

### ⚠️ Risk Notes
${a.risk_notes}

---
${ready ? "This issue is ready for implementation. Assign to \`@copilot\` or an engineer." : "⚠️ Needs clarification before work can begin."}

<sub>Generated by Triage Agent · powered by Claude via OpenRouter</sub>`;
}

function getLabels(a) {
  const labels = [];
  if (a.type === "bug") labels.push("bug");
  else if (a.type === "feature") labels.push("enhancement");
  else if (a.type === "chore") labels.push("chore");
  if (a.priority === "high") labels.push("high priority");
  else if (a.priority === "medium") labels.push("medium priority");
  else labels.push("low priority");
  labels.push(a.ready_for_implementation ? "ready-for-impl" : "needs-info");
  return labels;
}

async function main() {
  console.log(`Triage Agent processing issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}`);
  const analysis = await analyseIssue();
  console.log("Analysis:", JSON.stringify(analysis, null, 2));
  await postComment(formatComment(analysis));
  console.log("Posted engineering brief");
  const labels = getLabels(analysis);
  await addLabels(labels);
  console.log("Applied labels:", labels.join(", "));
}

main().catch((err) => { console.error("Triage Agent failed:", err); process.exit(1); });
